// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NearDupFinder_Almacenamiento;

#nullable disable

namespace NearDupFinder_Almacenamiento.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20251109162629_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NearDupFinder_Dominio.Clases.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Titulo")
                        .IsUnique();

                    b.ToTable("Catalogos", (string)null);
                });

            modelBuilder.Entity("NearDupFinder_Dominio.Clases.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CanonicoId")
                        .HasColumnType("int");

                    b.Property<int>("CatalogoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanonicoId");

                    b.HasIndex("CatalogoId");

                    b.ToTable("Clusters", (string)null);
                });

            modelBuilder.Entity("NearDupFinder_Dominio.Clases.EntradaDeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.ToTable("Auditorias", (string)null);
                });

            modelBuilder.Entity("NearDupFinder_Dominio.Clases.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CatalogoId")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstadoDuplicado")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoId");

                    b.HasIndex("ClusterId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("NearDupFinder_Dominio.Clases.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("NearDupFinder_Dominio.Clases.Cluster", b =>
                {
                    b.HasOne("NearDupFinder_Dominio.Clases.Item", "Canonico")
                        .WithMany()
                        .HasForeignKey("CanonicoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NearDupFinder_Dominio.Clases.Catalogo", null)
                        .WithMany("Clusters")
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canonico");
                });

            modelBuilder.Entity("NearDupFinder_Dominio.Clases.Item", b =>
                {
                    b.HasOne("NearDupFinder_Dominio.Clases.Catalogo", null)
                        .WithMany("Items")
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NearDupFinder_Dominio.Clases.Cluster", null)
                        .WithMany("PertenecientesCluster")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("NearDupFinder_Dominio.Clases.Usuario", b =>
                {
                    b.OwnsOne("NearDupFinder_Dominio.Clases.Clave", "Clave", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HashClave");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("NearDupFinder_Dominio.Clases.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("NearDupFinder_Dominio.Clases.Fecha", "FechaNacimiento", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<int>("Anio")
                                .HasColumnType("int")
                                .HasColumnName("AnioNacimiento");

                            b1.Property<int>("Dia")
                                .HasColumnType("int")
                                .HasColumnName("DiaNacimiento");

                            b1.Property<int>("Mes")
                                .HasColumnType("int")
                                .HasColumnName("MesNacimiento");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsMany("NearDupFinder_Dominio.Clases.RolPersistido", "RolesPersistidos", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Rol");

                            b1.HasKey("UsuarioId", "Valor");

                            b1.ToTable("UsuarioRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Clave")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FechaNacimiento")
                        .IsRequired();

                    b.Navigation("RolesPersistidos");
                });

            modelBuilder.Entity("NearDupFinder_Dominio.Clases.Catalogo", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("NearDupFinder_Dominio.Clases.Cluster", b =>
                {
                    b.Navigation("PertenecientesCluster");
                });
#pragma warning restore 612, 618
        }
    }
}
